### ISSUE TITLE
"Refused to load https://www.google.com/recaptcha/api.js?onload=ShowRecaptchaStandardLoginFormWebclient&render=explicit&_=1607777227272 because it appears in neither the script-src directive nor the default-src directive of the Content Security Policy."

### ISSUE THREAD

**Issue by Alseenrodelap** [afterlogic/aurora-module-webclient-recaptcha-plugin#1]
Hi,

I have a hosting company and I am testing out Webmail Pro for my users. While setting up recaptcha, the recaptcha field doesn't appear on the login screen. In the inspector I see the following message:

"Refused to load https://www.google.com/recaptcha/api.js?onload=ShowRecaptchaStandardLoginFormWebclient&render=explicit&_=1607777227272 because it appears in neither the script-src directive nor the default-src directive of the Content Security Policy."

Webmail Pro PHP version: 8.5.2-build-a3

**Comment by afterlogic-support** [comment]
We've corrected the issue and the fix will become available in the next release. To fix it on your installation, set the following value in `data/settings/config.json` file:

```json
"ContentSecurityPolicy": [
     "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: www.google.com www.gstatic.com; img-src * data: blob:; frame-src *",
     "string"
],
```

Thank you.
